# -*- coding: utf-8 -*-
"""Dataframe_task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VwdSOmFSIwS6I_aKYueM6Qj8V5PT4lGn

# **DataFrame Task By Vasudev.A**

### Exercise 1: Create a DataFrame from a Dictionary
- **Task**: Create a DataFrame using the following dictionary:
  ```python
  data = {
      'Product': ['Laptop', 'Phone', 'Tablet'],
      'Price': [1200, 800, 400],
      'Stock': [10, 50, 30]
  }
  ```
  - Display the DataFrame.
"""

import pandas as pd
data = {
    'Product': ['Laptop', 'Phone', 'Tablet'],
    'Price': [1200, 800, 400],
    'Stock': [10, 50, 30]
}

df = pd.DataFrame(data)
print(df)

"""### Exercise 2: Access a Column
- **Task**: From the DataFrame created in Exercise 1, access and print the **'Product'** column.

"""

print(df['Product'])

"""### Exercise 3: Add a New Column
- **Task**: Add a new column called **'Discount'** to the DataFrame with the values `[100, 50, 20]`.
"""

df['Discount'] = [100, 50, 20]
print(df)

"""### Exercise 4: Remove a Column
- **Task**: Remove the **'Stock'** column from the DataFrame using the `drop()` method, and display the updated DataFrame.
"""

df =df.drop('Stock', axis=1)
print(df)

"""### Exercise 5: Select a Row
- **Task**: Select and print the row for the **second product** using the `iloc[]` method.
"""

print(df.iloc[1])

"""### Exercise 6: Filter Data
- **Task**: Filter the DataFrame to display only products with a price greater than **500**.
"""

filtered_df = df[df['Price'] > 500]
print(filtered_df)

"""### Exercise 7: Create a DataFrame from a List
- **Task**: Create a DataFrame from the following list of lists:
  ```python
  data = [
      ['Alice', 24, 'Engineer'],
      ['Bob', 30, 'Doctor'],
      ['Charlie', 22, 'Artist']
  ]
  columns = ['Name', 'Age', 'Occupation']
  df = pd.DataFrame(data, columns=columns)
  ```
  - Display the DataFrame.
"""

import pandas as pd
data = [
    ['Alice', 24, 'Engineer'],
    ['Bob', 30, 'Doctor'],
    ['Charlie', 22, 'Artist']
]
columns = ['Name', 'Age', 'Occupation']
df = pd.DataFrame(data, columns=columns)
print(df)

"""### Exercise 8: Add Multiple Columns
- **Task**: To the DataFrame created in Exercise 7, add two new columns called **'Salary'** and **'Experience'** with values `[70000, 80000, 50000]` and `[2, 5, 1]` respectively.

"""

df['Salary']=[70000, 80000, 50000]
df['Experience'] = [2, 5, 1]
print(df)

"""### Exercise 9: Filter Rows Based on Multiple Conditions
- **Task**: From the DataFrame in Exercise 7, filter the rows where **'Age'** is greater than **25** and **'Occupation'** is **'Doctor'**.

"""

df_filter=df[(df['Age'] > 25) & (df['Occupation'] == 'Doctor')]
print(df_filter)

"""### Exercise 10: Modify a Column
- **Task**: Modify the **'Salary'** column in the DataFrame created in Exercise 7 by increasing each salary by **10%**, and display the updated DataFrame.
"""

import pandas as pd
data = [
    ['Alice', 24, 'Engineer'],
    ['Bob', 30, 'Doctor'],
    ['Charlie', 22, 'Artist']
]
columns = ['Name', 'Age', 'Occupation']
df = pd.DataFrame(data, columns=columns)
df['Salary']=[70000, 80000, 50000]
df['Experience'] = [2, 5, 1]
df['Salary'] = df['Salary'] * 1.1
print(df)

import pandas as pd
data = [
    ['Alice', 24, 'Engineer'],
    ['Bob', 30, 'Doctor'],
    ['Charlie', 22, 'Artist']
]
columns = ['Name', 'Age', 'Occupation']
df = pd.DataFrame(data, columns=columns)
df['Salary']=[70000, 80000, 50000]
df['Experience'] = [2, 5, 1]
df['Salary'] = df['Salary'] + df['Salary'] * (10/100)
print(df)